<a href="https://colab.research.google.com/github/yalex1402/AI_Course/blob/master/FindMatrixSolutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Find how many solutions do a linear system have?**

**By: Y. Alexander Garcia**

To find the number of solutions a linear system has is important to ***transform the matrix into a reduced echelon matrix.*** Once this is done, it’s necessary to validate if the new matrix has a ***contradiction or a [free variable](https://math.stackexchange.com/questions/720971/what-do-free-variable-and-leading-variables-mean)***.

First, the array size must be set (*remember that the matrix is A|B where A has a $m*n$ size*)


In [45]:
from sympy import Matrix
import numpy as np

def check_isnumber(text):
  if text.isnumeric():
    return True
  return False

def check_unique_solution():
    # Validate if the quantity of variables are grater than equations
    if int(quantity_columns)-1 > int(quantity_rows):
        return False
    # Validate if each variable has a pivot (1)
    i = 0
    leader_var_position = 0
    quantity_leading_var = 0
    m = reduced_echelon_matrix[0]
    while i < int(quantity_rows):        
        leader_var_position = ((int(quantity_columns)+1)*i)
        if leader_var_position > (int(quantity_rows)*int(quantity_columns)-2):
            break
        if m[leader_var_position] == 1 :
            quantity_leading_var += 1
        if quantity_leading_var == int(quantity_rows):
            return True
        i += 1
    # In other case
    return False

def check_no_solutions():
    position=0
    actual_row = 0
    actual_column = 0
    ban = False #Show if any row has all elements of A in (A|B) like 0
    m = reduced_echelon_matrix[0]
    while position < (int(quantity_rows)*int(quantity_columns)):
        #Check every position except the vector B 
        if position != (actual_row * int(quantity_columns))+(int(quantity_columns)-1):
            #validate if the elements in row are 0
            if m[position] == 0:
                ban = True
                actual_column += 1
            else:
                #if exits a number different to 0 jump to other row
                ban = False
                actual_row += 1
                position = int(quantity_rows)* actual_row
                actual_column = 0
                continue
        else:
            actual_row += 1
            actual_column = 0
        position += 1
    #Check if in the same row has a contradiction A = 0 but B != 0 in (A|B)
    if ban and (m[(int(quantity_columns)-1)+(int(quantity_columns) * (actual_row-1))]==0):
        ban = False
    return ban

# Matrix Size
print("Enter values to create a new matrix (A|B) where A has an m*n size. \n")
quantity_rows = input("Enter the number of rows: \n")
quantity_columns = input("Enter the number of columns: \n") #Include augmented matrix

# Validating the input written by users
while not(check_isnumber(quantity_rows)) or not(check_isnumber(quantity_columns)):
  print("You must write only numbers.\n")
  quantity_rows = input("Enter the number of rows:")
  quantity_columns = input("Enter the number of columns:")

Enter values to create a new matrix (A|B) where A has an m*n size. 

Enter the number of rows: 
3
Enter the number of columns: 
4


Then, the array is filled row by row and after that, it's reduced through rref() function.

In [46]:
matrix = []
row=[]
i = 0

#Generate matrix m*n
while i < int(quantity_rows):
  j=0
  row=[]
  while j < int(quantity_columns):
    row.append(float(input("Enter the number in position X" + str(i) + "," + str(j) + ": ")))
    j+=1
  matrix.append(row)
  i+=1

reduced_echelon_matrix = Matrix(matrix).rref()
print("original matrix: \n" ,np.matrix(matrix) ,"\n")
print("rref matrix: \n" , np.matrix(reduced_echelon_matrix[0]) ,"\n")

Enter the number in position X0,0: 20
Enter the number in position X0,1: 30
Enter the number in position X0,2: 20
Enter the number in position X0,3: 250
Enter the number in position X1,0: 20
Enter the number in position X1,1: 40
Enter the number in position X1,2: 10
Enter the number in position X1,3: 200
Enter the number in position X2,0: 40
Enter the number in position X2,1: 50
Enter the number in position X2,2: 50
Enter the number in position X2,3: 550
original matrix: 
 [[ 20.  30.  20. 250.]
 [ 20.  40.  10. 200.]
 [ 40.  50.  50. 550.]] 

rref matrix: 
 [[1 0 2.50000000000000 20.0000000000000]
 [0 1 -1.00000000000000 -5.00000000000000]
 [0 0 0 0]] 



Finally, the matrix should be analyzed to determine if it has one, many, or no solutions.

We know this:


1.   If there are more variables than equations, the linear system couldn't have a unique solution.
2.   If the system has a free variable and it doesn't have contradictions, it has infinite solutions.
3.   If exits one contradiction at least, the system doesn't have a solution.



In [47]:
if check_unique_solution():
    print("The system has unique solution")
elif check_no_solutions():
    print("The system doesn't have solution")
else:
    print("The system has multiple solutions")


The system has multiple solutions


# **Bibliography**

[Sympy Documentation](https://docs.sympy.org/latest/tutorial/matrices.html#rref) 

[Leading Variables and Free Variables](https://math.stackexchange.com/questions/720971/what-do-free-variable-and-leading-variables-mean)